# Generated by Django 4.0.6 on 2022-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
