# Generated by Django 4.0.6 on 2022-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('name', models.CharField(default='Test', max_length=100)),
                ('designation', models.CharField(default='Test', max_length=100)),
                ('objective', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('leetcode', models.CharField(blank=True, max_length=255)),
                ('hackerrank', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
