# Generated by Django 4.0.6 on 2022-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
